files:
  - source: /*.html
    translation: /%two_letters_code%/%original_path%/%original_file_name%
  - source: /updates/*.html
    translation: /%two_letters_code%/%original_path%/%original_file_name%
