files:
  - source: /src/main/resources/messages/*.properties
    ignore:
      - messages/*_ja.properties
      - messages/*_ko.properties
    translation: /src/main/resources/messages/%file_name%_%two_letters_code%.properties
